### ISSUE TITLE
Toggle

### ISSUE THREAD

**Issue by doragoncraft** [spikehidden/dTranslate#1]
/translationtoggle 

says deactivate but is still sending translated messages 

right hand side client
![image](https://user-images.githubusercontent.com/5422329/210453857-a3367b18-6def-4e30-9918-7d09677833a7.png)

**Comment by spikehidden** [comment]
Could you do the following:

- Run `/version` and paste the output here.
- Run `/version Denizen` and paste the output here.
- Create debug info by doing the following:
    1. Run `/denizen debug -r`
    2. Run the issuing command
    3. Run `/denizen submit`
    4. Post the link you get here.

**Comment by doragoncraft** [comment]
version
```om ran command: version
04.01 13:51:49 [Server] [INFO] Checking version, please wait...
04.01 13:51:49 [Server] [INFO] This server is running Paper version git-Paper-359 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 3331501)
04.01 13:51:49 [Server] [INFO] You are 9 version(s) behind
04.01 13:51:49 [Server] [INFO] Download the new version at: https://papermc.io/downloads
04.01 13:51:49 [Server] [INFO] Previous version: git-Paper-"476ef25" (MC: 1.19.2)
```
denizen
```om ran command: version Denizen
04.01 13:53:26 [Server] [INFO] Denizen version 1.2.6-SNAPSHOT (build 1782-REL)
04.01 13:53:26 [Server] [INFO] Author: The DenizenScript Team
```

debug
https://paste.denizenscript.com/View/104975

different response now 
![image](https://user-images.githubusercontent.com/5422329/210562222-8e1c2078-fae3-450c-908d-df4ad14494d4.png)

**Comment by spikehidden** [comment]
Could it be that you have the `*` permission or that your are OP?
Because the script is checking for the dTranslate.recieve permission and as and OP you have all permissions.
Please try again as non-OP.

**Comment by spikehidden** [comment]
Closing it as no more reply came from author.

Re-open it or create a new issue if the problem persists.
